### PR TITLE
[AKATSUKI] mixer_paths: Fix microphone low capture volume

### PR DESCRIPTION
**Pull request by kholk**
The microphone volume was very low and the other end could
only barely hear. Now it's fine :)))

P.S.: Should this be ported on all Tama devices?

### CODE REVIEW

**Comment by MartinX3** [comment]
@kholk As far as I know the entire tama board has this problem :)

**Comment by jerpelea** [comment]
done for all

**Comment by MarijnS95** [comment]
This raises the burning questions:

- Why was it working just fine before (iirc... 4.9 times, or before the CAF HAL)?
- Why does stock not need higher values (sure, they use different paths, but all paths have been updated in this PR)?

Perhaps the CAF HAL is doing things "differently" that only affect Tama?

**Comment by MartinX3** [comment]
@MarijnS95 I heard from vanilla stock users saying the record volume is too low for their whatsapp recordings since 10.0

**Comment by MarijnS95** [comment]
@MartinX3 Ah, that might explain why we see different volumes in different paths and (iirc, this was months ago) little difference between mixer_paths.xml here in SODP and in an A10 dump. Thanks for mentioning!

**Pull request merged**
